/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IngredientRouteImport } from './routes/ingredient'
import { Route as IngredientTwoRouteImport } from './routes/ingredient-two'
import { Route as KategoriteRouteImport } from './routes/kategorite'
import { Route as KontaktiRouteImport } from './routes/kontakti'
import { Route as ParollerRouteImport } from './routes/paroller'
import { Route as ProduktetRouteImport } from './routes/produktet'
import { Route as PyetjeRouteImport } from './routes/pyetje'
import { Route as RrethNeshRouteImport } from './routes/rreth-nesh'
import { Route as ShopDetailsRouteImport } from './routes/shop-details'
import { Route as ShportaRouteImport } from './routes/shporta'
import { Route as AdminSplatRouteImport } from './routes/admin.$'
import { Route as KategoriaSlugRouteImport } from './routes/kategoria.$slug'
import { Route as ShopDetailsIdRouteImport } from './routes/shop-details.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientRoute = IngredientRouteImport.update({
  id: '/ingredient',
  path: '/ingredient',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientTwoRoute = IngredientTwoRouteImport.update({
  id: '/ingredient-two',
  path: '/ingredient-two',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriteRoute = KategoriteRouteImport.update({
  id: '/kategorite',
  path: '/kategorite',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktiRoute = KontaktiRouteImport.update({
  id: '/kontakti',
  path: '/kontakti',
  getParentRoute: () => rootRouteImport,
} as any)
const ParollerRoute = ParollerRouteImport.update({
  id: '/paroller',
  path: '/paroller',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduktetRoute = ProduktetRouteImport.update({
  id: '/produktet',
  path: '/produktet',
  getParentRoute: () => rootRouteImport,
} as any)
const PyetjeRoute = PyetjeRouteImport.update({
  id: '/pyetje',
  path: '/pyetje',
  getParentRoute: () => rootRouteImport,
} as any)
const RrethNeshRoute = RrethNeshRouteImport.update({
  id: '/rreth-nesh',
  path: '/rreth-nesh',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopDetailsRoute = ShopDetailsRouteImport.update({
  id: '/shop-details',
  path: '/shop-details',
  getParentRoute: () => rootRouteImport,
} as any)
const ShportaRoute = ShportaRouteImport.update({
  id: '/shporta',
  path: '/shporta',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/admin/$',
  path: '/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriaSlugRoute = KategoriaSlugRouteImport.update({
  id: '/kategoria/$slug',
  path: '/kategoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopDetailsIdRoute = ShopDetailsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShopDetailsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ingredient': typeof IngredientRoute
  '/ingredient-two': typeof IngredientTwoRoute
  '/kategorite': typeof KategoriteRoute
  '/kontakti': typeof KontaktiRoute
  '/paroller': typeof ParollerRoute
  '/produktet': typeof ProduktetRoute
  '/pyetje': typeof PyetjeRoute
  '/rreth-nesh': typeof RrethNeshRoute
  '/shop-details': typeof ShopDetailsRouteWithChildren
  '/shporta': typeof ShportaRoute
  '/admin/$': typeof AdminSplatRoute
  '/kategoria/$slug': typeof KategoriaSlugRoute
  '/shop-details/$id': typeof ShopDetailsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ingredient': typeof IngredientRoute
  '/ingredient-two': typeof IngredientTwoRoute
  '/kategorite': typeof KategoriteRoute
  '/kontakti': typeof KontaktiRoute
  '/paroller': typeof ParollerRoute
  '/produktet': typeof ProduktetRoute
  '/pyetje': typeof PyetjeRoute
  '/rreth-nesh': typeof RrethNeshRoute
  '/shop-details': typeof ShopDetailsRouteWithChildren
  '/shporta': typeof ShportaRoute
  '/admin/$': typeof AdminSplatRoute
  '/kategoria/$slug': typeof KategoriaSlugRoute
  '/shop-details/$id': typeof ShopDetailsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ingredient': typeof IngredientRoute
  '/ingredient-two': typeof IngredientTwoRoute
  '/kategorite': typeof KategoriteRoute
  '/kontakti': typeof KontaktiRoute
  '/paroller': typeof ParollerRoute
  '/produktet': typeof ProduktetRoute
  '/pyetje': typeof PyetjeRoute
  '/rreth-nesh': typeof RrethNeshRoute
  '/shop-details': typeof ShopDetailsRouteWithChildren
  '/shporta': typeof ShportaRoute
  '/admin/$': typeof AdminSplatRoute
  '/kategoria/$slug': typeof KategoriaSlugRoute
  '/shop-details/$id': typeof ShopDetailsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ingredient'
    | '/ingredient-two'
    | '/kategorite'
    | '/kontakti'
    | '/paroller'
    | '/produktet'
    | '/pyetje'
    | '/rreth-nesh'
    | '/shop-details'
    | '/shporta'
    | '/admin/$'
    | '/kategoria/$slug'
    | '/shop-details/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ingredient'
    | '/ingredient-two'
    | '/kategorite'
    | '/kontakti'
    | '/paroller'
    | '/produktet'
    | '/pyetje'
    | '/rreth-nesh'
    | '/shop-details'
    | '/shporta'
    | '/admin/$'
    | '/kategoria/$slug'
    | '/shop-details/$id'
  id:
    | '__root__'
    | '/'
    | '/ingredient'
    | '/ingredient-two'
    | '/kategorite'
    | '/kontakti'
    | '/paroller'
    | '/produktet'
    | '/pyetje'
    | '/rreth-nesh'
    | '/shop-details'
    | '/shporta'
    | '/admin/$'
    | '/kategoria/$slug'
    | '/shop-details/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IngredientRoute: typeof IngredientRoute
  IngredientTwoRoute: typeof IngredientTwoRoute
  KategoriteRoute: typeof KategoriteRoute
  KontaktiRoute: typeof KontaktiRoute
  ParollerRoute: typeof ParollerRoute
  ProduktetRoute: typeof ProduktetRoute
  PyetjeRoute: typeof PyetjeRoute
  RrethNeshRoute: typeof RrethNeshRoute
  ShopDetailsRoute: typeof ShopDetailsRouteWithChildren
  ShportaRoute: typeof ShportaRoute
  AdminSplatRoute: typeof AdminSplatRoute
  KategoriaSlugRoute: typeof KategoriaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredient': {
      id: '/ingredient'
      path: '/ingredient'
      fullPath: '/ingredient'
      preLoaderRoute: typeof IngredientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredient-two': {
      id: '/ingredient-two'
      path: '/ingredient-two'
      fullPath: '/ingredient-two'
      preLoaderRoute: typeof IngredientTwoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategorite': {
      id: '/kategorite'
      path: '/kategorite'
      fullPath: '/kategorite'
      preLoaderRoute: typeof KategoriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakti': {
      id: '/kontakti'
      path: '/kontakti'
      fullPath: '/kontakti'
      preLoaderRoute: typeof KontaktiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paroller': {
      id: '/paroller'
      path: '/paroller'
      fullPath: '/paroller'
      preLoaderRoute: typeof ParollerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produktet': {
      id: '/produktet'
      path: '/produktet'
      fullPath: '/produktet'
      preLoaderRoute: typeof ProduktetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pyetje': {
      id: '/pyetje'
      path: '/pyetje'
      fullPath: '/pyetje'
      preLoaderRoute: typeof PyetjeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rreth-nesh': {
      id: '/rreth-nesh'
      path: '/rreth-nesh'
      fullPath: '/rreth-nesh'
      preLoaderRoute: typeof RrethNeshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop-details': {
      id: '/shop-details'
      path: '/shop-details'
      fullPath: '/shop-details'
      preLoaderRoute: typeof ShopDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shporta': {
      id: '/shporta'
      path: '/shporta'
      fullPath: '/shporta'
      preLoaderRoute: typeof ShportaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/admin/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategoria/$slug': {
      id: '/kategoria/$slug'
      path: '/kategoria/$slug'
      fullPath: '/kategoria/$slug'
      preLoaderRoute: typeof KategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop-details/$id': {
      id: '/shop-details/$id'
      path: '/$id'
      fullPath: '/shop-details/$id'
      preLoaderRoute: typeof ShopDetailsIdRouteImport
      parentRoute: typeof ShopDetailsRoute
    }
  }
}

interface ShopDetailsRouteChildren {
  ShopDetailsIdRoute: typeof ShopDetailsIdRoute
}

const ShopDetailsRouteChildren: ShopDetailsRouteChildren = {
  ShopDetailsIdRoute: ShopDetailsIdRoute,
}

const ShopDetailsRouteWithChildren = ShopDetailsRoute._addFileChildren(
  ShopDetailsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IngredientRoute: IngredientRoute,
  IngredientTwoRoute: IngredientTwoRoute,
  KategoriteRoute: KategoriteRoute,
  KontaktiRoute: KontaktiRoute,
  ParollerRoute: ParollerRoute,
  ProduktetRoute: ProduktetRoute,
  PyetjeRoute: PyetjeRoute,
  RrethNeshRoute: RrethNeshRoute,
  ShopDetailsRoute: ShopDetailsRouteWithChildren,
  ShportaRoute: ShportaRoute,
  AdminSplatRoute: AdminSplatRoute,
  KategoriaSlugRoute: KategoriaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
