/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CartRouteImport } from './routes/cart'
import { Route as IngredientRouteImport } from './routes/ingredient'
import { Route as IngredientTwoRouteImport } from './routes/ingredient-two'
import { Route as ParollerRouteImport } from './routes/paroller'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShopDetailsRouteImport } from './routes/shop-details'
import { Route as AdminSplatRouteImport } from './routes/admin.$'
import { Route as KategoriaSlugRouteImport } from './routes/kategoria.$slug'
import { Route as ShopDetailsIdRouteImport } from './routes/shop-details.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientRoute = IngredientRouteImport.update({
  id: '/ingredient',
  path: '/ingredient',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientTwoRoute = IngredientTwoRouteImport.update({
  id: '/ingredient-two',
  path: '/ingredient-two',
  getParentRoute: () => rootRouteImport,
} as any)
const ParollerRoute = ParollerRouteImport.update({
  id: '/paroller',
  path: '/paroller',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopDetailsRoute = ShopDetailsRouteImport.update({
  id: '/shop-details',
  path: '/shop-details',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/admin/$',
  path: '/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriaSlugRoute = KategoriaSlugRouteImport.update({
  id: '/kategoria/$slug',
  path: '/kategoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopDetailsIdRoute = ShopDetailsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ShopDetailsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/ingredient': typeof IngredientRoute
  '/ingredient-two': typeof IngredientTwoRoute
  '/paroller': typeof ParollerRoute
  '/shop': typeof ShopRoute
  '/shop-details': typeof ShopDetailsRouteWithChildren
  '/admin/$': typeof AdminSplatRoute
  '/kategoria/$slug': typeof KategoriaSlugRoute
  '/shop-details/$id': typeof ShopDetailsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/ingredient': typeof IngredientRoute
  '/ingredient-two': typeof IngredientTwoRoute
  '/paroller': typeof ParollerRoute
  '/shop': typeof ShopRoute
  '/shop-details': typeof ShopDetailsRouteWithChildren
  '/admin/$': typeof AdminSplatRoute
  '/kategoria/$slug': typeof KategoriaSlugRoute
  '/shop-details/$id': typeof ShopDetailsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/ingredient': typeof IngredientRoute
  '/ingredient-two': typeof IngredientTwoRoute
  '/paroller': typeof ParollerRoute
  '/shop': typeof ShopRoute
  '/shop-details': typeof ShopDetailsRouteWithChildren
  '/admin/$': typeof AdminSplatRoute
  '/kategoria/$slug': typeof KategoriaSlugRoute
  '/shop-details/$id': typeof ShopDetailsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cart'
    | '/ingredient'
    | '/ingredient-two'
    | '/paroller'
    | '/shop'
    | '/shop-details'
    | '/admin/$'
    | '/kategoria/$slug'
    | '/shop-details/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/ingredient'
    | '/ingredient-two'
    | '/paroller'
    | '/shop'
    | '/shop-details'
    | '/admin/$'
    | '/kategoria/$slug'
    | '/shop-details/$id'
  id:
    | '__root__'
    | '/'
    | '/cart'
    | '/ingredient'
    | '/ingredient-two'
    | '/paroller'
    | '/shop'
    | '/shop-details'
    | '/admin/$'
    | '/kategoria/$slug'
    | '/shop-details/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CartRoute: typeof CartRoute
  IngredientRoute: typeof IngredientRoute
  IngredientTwoRoute: typeof IngredientTwoRoute
  ParollerRoute: typeof ParollerRoute
  ShopRoute: typeof ShopRoute
  ShopDetailsRoute: typeof ShopDetailsRouteWithChildren
  AdminSplatRoute: typeof AdminSplatRoute
  KategoriaSlugRoute: typeof KategoriaSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredient': {
      id: '/ingredient'
      path: '/ingredient'
      fullPath: '/ingredient'
      preLoaderRoute: typeof IngredientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredient-two': {
      id: '/ingredient-two'
      path: '/ingredient-two'
      fullPath: '/ingredient-two'
      preLoaderRoute: typeof IngredientTwoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paroller': {
      id: '/paroller'
      path: '/paroller'
      fullPath: '/paroller'
      preLoaderRoute: typeof ParollerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop-details': {
      id: '/shop-details'
      path: '/shop-details'
      fullPath: '/shop-details'
      preLoaderRoute: typeof ShopDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/admin/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategoria/$slug': {
      id: '/kategoria/$slug'
      path: '/kategoria/$slug'
      fullPath: '/kategoria/$slug'
      preLoaderRoute: typeof KategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop-details/$id': {
      id: '/shop-details/$id'
      path: '/$id'
      fullPath: '/shop-details/$id'
      preLoaderRoute: typeof ShopDetailsIdRouteImport
      parentRoute: typeof ShopDetailsRoute
    }
  }
}

interface ShopDetailsRouteChildren {
  ShopDetailsIdRoute: typeof ShopDetailsIdRoute
}

const ShopDetailsRouteChildren: ShopDetailsRouteChildren = {
  ShopDetailsIdRoute: ShopDetailsIdRoute,
}

const ShopDetailsRouteWithChildren = ShopDetailsRoute._addFileChildren(
  ShopDetailsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CartRoute: CartRoute,
  IngredientRoute: IngredientRoute,
  IngredientTwoRoute: IngredientTwoRoute,
  ParollerRoute: ParollerRoute,
  ShopRoute: ShopRoute,
  ShopDetailsRoute: ShopDetailsRouteWithChildren,
  AdminSplatRoute: AdminSplatRoute,
  KategoriaSlugRoute: KategoriaSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
